DRAFT_STATUS = 1
DUMMY_STATUS = 2
PUBLISHED_STATUS = 3
REMOVED_STATUS = 4
SCHEDULED_STATUS = 5

STATUS_CHOICES = (
        (DRAFT_STATUS, 'Draft'),
        (DUMMY_STATUS, 'Dummy'),
        (PUBLISHED_STATUS, 'Published'),
        (REMOVED_STATUS, 'Removed'),
        (SCHEDULED_STATUS, 'Scheduled'),
    )